### ISSUE TITLE
Confirm patch on ERS calculations

### ISSUE THREAD

**Issue by fergusoa** [NRCan-IETS-CE-O-HBC/HousingModels#11]
Welcome back Jeff!

When you get in on Monday AM, please make verifying this patch your first order of buisness: https://github.com/NRCan-IETS-CE-O-HBC/HousingModels/commit/f64bf97. We're running optimizations with this patch in place and need to know if we can trust the resulting #s.

**Comment by jblake59** [comment]
Confirmed fix!
